### ISSUE TITLE
Can we stop license rumors?

### ISSUE THREAD

**Issue by tico-tico** [nu774/fdkaac#35]
There is a bunch of weird sjw guys spreading misinformation about FDK-AAC license, so I have a proposal to stop the rumors and just include the FDK-AAC license directly in the executable. It is required to distribute the license with the binary anyway. The license said "or other materials", so I think that binary guts are quite an "other material".

> Redistribution and use in source and binary forms, with or without modification,
> are permitted without payment of copyright license fees provided that you
> satisfy the following conditions:
> 
> You must retain the complete text of this software license in redistributions of
> the FDK AAC Codec or your modifications thereto in source code form.
> 
> You must retain the complete text of this software license in the documentation
> and/or other materials provided with redistributions of the FDK AAC Codec or
> your modifications thereto in binary form. You must make available free of
> charge copies of the complete source code of the FDK AAC Codec and your
> modifications thereto to recipients of copies in binary form.

Therefore I propose to do something like this https://github.com/nu774/fdkaac/compare/master...tico-tico:fdk_license . I'll do the pull request if you like the idea.

**Comment by nu774** [comment]
Hi,
As far as I know, distros such as Debian or Cygwin include copyright text of the FDK codec in their libfdk-aac package distribution (it's installed under /user/share/doc/ or something).
fdkaac and libfdk-aac.so are different thing, and they do need to provide license documentation for codec itself (libfdk-aac.so) in order to distribute libfdk-aac.so.
In other words, I don't think it's something that fdkaac repo has to take care of. We are not re-distributing the FDK codec.
